export default defineEventHandler(() => {
    const featureData = [
        {
            img: "/images/kathmandu.webp",
            title: "Kathmandu",
            price: 5500,
            person: 120,
            location: "Nepal",
            days: 5,
            slug: "Kathmandu",
        },
        {
            img: "/images/kathmandu2.webp",
            title: "Kathmandu Durbar Square",
            price: 4500,
            person: 80,
            location: "Nepal",
            days: 3,
            slug: "Kathmandu",
        },
        {
            img: "/images/pokhara.webp",
            title: "Pokhara Lakeside",
            price: 6500,
            person: 150,
            location: "Nepal",
            days: 7,
            slug: "Pokhara",
        },
        {
            img: "/images/pokhara2.webp",
            title: "Sarangkot Sunrise Tour",
            price: 4000,
            person: 60,
            location: "Nepal",
            days: 2,
            slug: "Pokhara",
        },
        {
            img: "/images/lumbini.webp",
            title: "Lumbini Pilgrimage",
            price: 7000,
            person: 50,
            location: "Nepal",
            days: 8,
            slug: "Lumbini",
        },
        {
            img: "/images/lumbini2.webp",
            title: "Birthplace of Buddha Tour",
            price: 7500,
            person: 40,
            location: "Nepal",
            days: 9,
            slug: "Lumbini",
        },
        {
            img: "/images/bharatnager.webp",
            title: "Dharan City Exploration",
            price: 6000,
            person: 90,
            location: "Nepal",
            days: 6,
            slug: "Dharan",
        },
        {
            img: "/images/dh.webp",
            title: "Dharan Hiking Tour",
            price: 5000,
            person: 70,
            location: "Nepal",
            days: 4,
            slug: "Dharan",
        },
        {
            img: "../../public/images/dh3.webp",
            title: "Biratnagar City Tour",
            price: 4000,
            person: 85,
            location: "Nepal",
            days: 3,
            slug: "Biratnagar",
        },
        {
            img: "/images/dharan2.webp",
            title: "Biratnagar Cultural Experience",
            price: 4500,
            person: 95,
            location: "Nepal",
            days: 5,
            slug: "Biratnagar",
        },
    ];

    return featureData;
});
